info:
  title: OSZO Digital Health API
  version: 1.0.0
openapi: 3.0.0
paths:
  /api/consultas:
    get:
      summary: Listar consultas
      parameters:
        - in: query
          name: paciente_id
          schema:
            type: integer
          required: false
          description: Filtrar consultas por ID do paciente
        - in: query
          name: status
          schema:
            type: string
          required: false
          description: Filtrar consultas por status
      responses:
        '200':
          description: Lista de consultas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consulta'
    post:
      summary: Agendar nova consulta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Consulta'
      responses:
        '201':
          description: Consulta agendada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consulta'
  /api/consultas/{consulta_id}:
    get:
      summary: Obter consulta por ID
      parameters:
        - in: path
          name: consulta_id
          schema:
            type: integer
          required: true
          description: ID da consulta
      responses:
        '200':
          description: Detalhes da consulta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consulta'
        '404':
          description: Consulta não encontrada
    put:
      summary: Atualizar consulta
      parameters:
        - in: path
          name: consulta_id
          schema:
            type: integer
          required: true
          description: ID da consulta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Consulta'
      responses:
        '200':
          description: Consulta atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consulta'
    delete:
      summary: Cancelar consulta
      parameters:
        - in: path
          name: consulta_id
          schema:
            type: integer
          required: true
          description: ID da consulta
      responses:
        '204':
          description: Consulta cancelada com sucesso
  /api/documentos:
    get:
      summary: Listar documentos médicos
    post:
      summary: Adicionar novo documento
  /api/health:
    get:
      summary: Verificar saúde da API
  /api/medicos:
    get:
      summary: Listar médicos
      parameters:
        - in: query
          name: specialty
          schema:
            type: string
          required: false
          description: Filtrar médicos por especialidade
      responses:
        '200':
          description: Lista de médicos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Medico'
    post:
      summary: Criar novo médico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Medico'
      responses:
        '201':
          description: Médico criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medico'
  /api/medicos/{medico_id}:
    get:
      summary: Obter médico por ID
      parameters:
        - in: path
          name: medico_id
          schema:
            type: integer
          required: true
          description: ID do médico
      responses:
        '200':
          description: Detalhes do médico
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medico'
        '404':
          description: Médico não encontrado
  /api/medicos/{medico_id}/horarios:
    get:
      summary: Listar horários disponíveis de um médico
      parameters:
        - in: path
          name: medico_id
          schema:
            type: integer
          required: true
          description: ID do médico
        - in: query
          name: data
          schema:
            type: string
            format: date
          required: false
          description: Filtrar horários por data (YYYY-MM-DD)
      responses:
        '200':
          description: Lista de horários disponíveis
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HorarioDisponivel'
  /api/especialidades:
    get:
      summary: Listar especialidades médicas
      responses:
        '200':
          description: Lista de especialidades
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/notificacoes:
    get:
      summary: Listar notificações
      parameters:
        - in: query
          name: usuario_id
          schema:
            type: integer
          required: false
          description: Filtrar notificações por ID do usuário
        - in: query
          name: read
          schema:
            type: boolean
          required: false
          description: Filtrar notificações por status de leitura
      responses:
        '200':
          description: Lista de notificações
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notificacao'
    post:
      summary: Criar nova notificação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notificacao'
      responses:
        '201':
          description: Notificação criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notificacao'
  /api/notificacoes/{notificacao_id}:
    get:
      summary: Obter notificação por ID
      parameters:
        - in: path
          name: notificacao_id
          schema:
            type: integer
          required: true
          description: ID da notificação
      responses:
        '200':
          description: Detalhes da notificação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notificacao'
        '404':
          description: Notificação não encontrada
    put:
      summary: Atualizar status da notificação
      parameters:
        - in: path
          name: notificacao_id
          schema:
            type: integer
          required: true
          description: ID da notificação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notificacao'
      responses:
        '200':
          description: Notificação atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notificacao'
    delete:
      summary: Excluir notificação
      parameters:
        - in: path
          name: notificacao_id
          schema:
            type: integer
          required: true
          description: ID da notificação
      responses:
        '204':
          description: Notificação excluída com sucesso
  /api/notificacoes/{notificacao_id}/marcar-lida:
    put:
      summary: Marcar notificação como lida
      parameters:
        - in: path
          name: notificacao_id
          schema:
            type: integer
          required: true
          description: ID da notificação
      responses:
        '200':
          description: Notificação marcada como lida com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notificacao'
  /api/users:
    get:
      summary: Listar usuários
      responses:
        '200':
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Criar novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/users/{user_id}:
    get:
      summary: Obter usuário por ID
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: true
          description: ID do usuário
      responses:
        '200':
          description: Detalhes do usuário
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Usuário não encontrado
  /api/auth/login:
    post:
      summary: Autenticar usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
                  description: Email ou CPF do usuário
                password:
                  type: string
                  description: Senha do usuário
              required:
                - identifier
                - password
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Credenciais inválidas


components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email
        cpf:
          type: string
        avatar:
          type: string
        password:
          type: string
        user_type:
          type: string
        telefone:
          type: string
        idade:
          type: integer
        family_id:
          type: string
        created_at:
          type: string
          format: date-time
    Medico:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        specialty:
          type: string
        rating:
          type: number
          format: float
        price:
          type: number
          format: float
        image:
          type: string
        crm:
          type: string
        telefone:
          type: string
        unidade:
          type: string
        disponibilidade:
          type: string
        created_at:
          type: string
          format: date-time
    HorarioDisponivel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        medico_id:
          type: integer
          format: int64
        data:
          type: string
          format: date
        hora_inicio:
          type: string
          format: time
        hora_fim:
          type: string
          format: time
        disponivel:
          type: boolean
        tipo_atendimento:
          type: string
    Consulta:
      type: object
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
        specialty:
          type: string
        medico_id:
          type: integer
          format: int64
        paciente_id:
          type: integer
          format: int64
        slot_id:
          type: integer
          format: int64
        data:
          type: string
          format: date
        hora:
          type: string
          format: time
        status:
          type: string
        link_meet:
          type: string
        unidade:
          type: string
        observacoes:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time


